name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies
      - run: npm install

      # Build app
      - run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages      # Target branch
          folder: dist          # Folder to deploy
          clean: true           # Remove old files
          token: ${{ secrets.GITHUB_TOKEN }}
